#autogenerate by ./install.sh (2017-07-18)

# folders which be build during the bulding process
# they are name free
LIB_dir =  $(shell pwd)/lib

# compiler
#CXX = clang++
#CFLAGS = -std=c++1y -stdlib=libc++   

# if you want to switch compiler : make switch COMPILER=g++
CXX = g++-8 -std=c++14
#CXX = clang++ -std=c++1y -stdlib=libc++
#CXX = scan-build -v -k --force-analyze-debug-code -o html clang++ -std=c++1y -stdlib=libc++
